name: Terraform Plan

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::853106001369:role/ai-mentoring-github-actions
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform plan
        env:
          TF_VAR_notification_email: ${{ secrets.NOTIFICATION_EMAIL }}
          TF_VAR_project_name: ${{ vars.PROJECT_NAME }}
          TF_VAR_environment: ${{ vars.ENVIRONMENT }}
          TF_VAR_github_access_token: ${{ secrets.GH_PAT_AMPLIFY }}
          TF_VAR_api_gateway_url: ${{ vars.API_GATEWAY_URL }}
          TF_VAR_cognito_user_pool_id: ${{ vars.COGNITO_USER_POOL_ID }}
          TF_VAR_cognito_client_id: ${{ vars.COGNITO_CLIENT_ID }}
          